/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_multiply_13 (
    input [7:0] a,
    input [7:0] b,
    output reg [15:0] result
  );
  
  
  
  reg [15:0] p0;
  
  reg [15:0] p1;
  
  reg [15:0] p2;
  
  reg [15:0] p3;
  
  reg [15:0] p4;
  
  reg [15:0] p5;
  
  reg [15:0] p6;
  
  reg [15:0] p7;
  
  always @* begin
    p0[0+7-:8] = ({4'h8{a[0+0-:1]}}) & (b[0+7-:8]);
    p1[1+7-:8] = (({4'h8{a[1+0-:1]}}) & (b[0+7-:8]));
    p2[2+7-:8] = (({4'h8{a[2+0-:1]}}) & (b[0+7-:8]));
    p3[3+7-:8] = (({4'h8{a[3+0-:1]}}) & (b[0+7-:8]));
    p4[4+7-:8] = (({4'h8{a[4+0-:1]}}) & (b[0+7-:8]));
    p5[5+7-:8] = (({4'h8{a[5+0-:1]}}) & (b[0+7-:8]));
    p6[6+7-:8] = (({4'h8{a[6+0-:1]}}) & (b[0+7-:8]));
    p7[7+7-:8] = (({4'h8{a[7+0-:1]}}) & (b[0+7-:8]));
    p0[8+7-:8] = 8'h00;
    p1[9+6-:7] = 7'h00;
    p2[10+5-:6] = 6'h00;
    p3[11+4-:5] = 5'h00;
    p4[12+3-:4] = 4'h0;
    p5[13+2-:3] = 3'h0;
    p6[14+1-:2] = 2'h0;
    p7[15+0-:1] = 1'h0;
    result = p0 + p1 + p2 + p3 + p4 + p5 + p6 + p7;
  end
endmodule
