/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module button_manager_2 (
    input clk,
    input rst,
    input [5:0] buttonRaw,
    input [5:0] buttonSeen,
    output reg [5:0] buttonPressedOut
  );
  
  
  
  reg [5:0] M_buttonPressed_d, M_buttonPressed_q = 1'h0;
  
  reg [5:0] M_buttonReady_d, M_buttonReady_q = 1'h0;
  
  wire [(3'h6+0)-1:0] M_cond_out;
  reg [(3'h6+0)-1:0] M_cond_in;
  
  genvar GEN_cond0;
  generate
  for (GEN_cond0=0;GEN_cond0<3'h6;GEN_cond0=GEN_cond0+1) begin: cond_gen_0
    button_conditioner_6 cond (
      .clk(clk),
      .in(M_cond_in[GEN_cond0*(1)+(1)-1-:(1)]),
      .out(M_cond_out[GEN_cond0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  integer i;
  
  always @* begin
    M_buttonReady_d = M_buttonReady_q;
    M_buttonPressed_d = M_buttonPressed_q;
    
    M_cond_in = buttonRaw;
    for (i = 1'h0; i < 3'h6; i = i + 1) begin
      if (M_cond_out[(i)*1+0-:1]) begin
        if (M_buttonReady_q[(i)*1+0-:1]) begin
          M_buttonReady_d[(i)*1+0-:1] = 1'h0;
          M_buttonPressed_d[(i)*1+0-:1] = 1'h1;
        end
      end else begin
        M_buttonReady_d[(i)*1+0-:1] = 1'h1;
        M_buttonPressed_d[(i)*1+0-:1] = 1'h0;
      end
      if (buttonSeen[(i)*1+0-:1]) begin
        M_buttonPressed_d[(i)*1+0-:1] = 1'h0;
      end
    end
    buttonPressedOut = M_buttonPressed_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_buttonReady_q <= 1'h0;
    end else begin
      M_buttonReady_q <= M_buttonReady_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_buttonPressed_q <= 1'h0;
    end else begin
      M_buttonPressed_q <= M_buttonPressed_d;
    end
  end
  
endmodule
