/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_compare_11 (
    input [5:0] alufn,
    input v,
    input z,
    input n,
    output reg [15:0] result
  );
  
  
  
  reg comparison;
  
  always @* begin
    
    case (alufn[1+1-:2])
      2'h1: begin
        comparison = z;
      end
      2'h2: begin
        comparison = n ^ v;
      end
      2'h3: begin
        comparison = z | (n ^ v);
      end
      default: begin
        comparison = 1'h0;
      end
    endcase
    result = {15'h0000, comparison};
  end
endmodule
